=== britzke/rennspur/datasets/countries/countries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<element name="countries">
		<complexType>
			<sequence maxOccurs="unbounded">
				<element name="country">
					<complexType>
						<all>
							<element name="name" type="string" />
							<element name="code" type="short" minOccurs="0"/>
							<element name="a2code" type="string" minOccurs="0"/>
							<element name="a3code" type="string" minOccurs="0"/>
							<element name="mnacode" type="string" minOccurs="0"/>
							<element name="mnagroup" type="string" minOccurs="0"/>
							<element name="since" type="short" minOccurs="0"/>
							<element name="note" type="string" minOccurs="0"/>
						</all>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== britzke/rennspur/datasets/countries/ISO 3166-1 alpha-2.out.xml
<?xml version="1.0" encoding="utf-8"?>
<countries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="countries.xsd">
	<country>
		<a2code>AD</a2code>
		<name>Andorra</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>AE</a2code>
		<name>United Arab Emirates</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>AF</a2code>
		<name>Afghanistan</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>AG</a2code>
		<name>Antigua and Barbuda</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>AI</a2code>
		<name>Anguilla</name>
		<since>1983</since>
		<note>AI previously represented French Afar and Issas</note>
	</country>
	<country>
		<a2code>AL</a2code>
		<name>Albania</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>AM</a2code>
		<name>Armenia</name>
		<since>1992</since>
		<note />
	</country>
	<country>
		<a2code>AO</a2code>
		<name>Angola</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>AQ</a2code>
		<name>Antarctica</name>
		<since>1974</since>
		<note>Covers the territories south of 60° south latitude Code taken from name in Antarctique</note>
	</country>
	<country>
		<a2code>AR</a2code>
		<name>Argentina</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>AS</a2code>
		<name>American Samoa</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>AT</a2code>
		<name>Austria</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>AU</a2code>
		<name>Australia</name>
		<since>1974</since>
		<note>Includes the Coral Sea Islands</note>
	</country>
	<country>
		<a2code>AW</a2code>
		<name>Aruba</name>
		<since>1986</since>
		<note />
	</country>
	<country>
		<a2code>AX</a2code>
		<name>Åland Islands</name>
		<since>2004</since>
		<note>An autonomous province of Finland</note>
	</country>
	<country>
		<a2code>AZ</a2code>
		<name>Azerbaijan</name>
		<since>1992</since>
		<note />
	</country>
	<country>
		<a2code>BA</a2code>
		<name>Bosnia and Herzegovina</name>
		<since>1992</since>
		<note />
	</country>
	<country>
		<a2code>BB</a2code>
		<name>Barbados</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BD</a2code>
		<name>Bangladesh</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BE</a2code>
		<name>Belgium</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BF</a2code>
		<name>Burkina Faso</name>
		<since>1984</since>
		<note>Name changed from Upper Volta (HV)</note>
	</country>
	<country>
		<a2code>BG</a2code>
		<name>Bulgaria</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BH</a2code>
		<name>Bahrain</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BI</a2code>
		<name>Burundi</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BJ</a2code>
		<name>Benin</name>
		<since>1977</since>
		<note>Name changed from Dahomey (DY)</note>
	</country>
	<country>
		<a2code>BL</a2code>
		<name>Saint Barthélemy</name>
		<since>2007</since>
		<note />
	</country>
	<country>
		<a2code>BM</a2code>
		<name>Bermuda</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BN</a2code>
		<name>Brunei Darussalam</name>
		<since>1974</since>
		<note>ISO country name follows UN designation (common name: Brunei)</note>
	</country>
	<country>
		<a2code>BO</a2code>
		<name>Bolivia, Plurinational State of</name>
		<since>1974</since>
		<note>ISO country name follows UN designation (common name and previous ISO country name: Bolivia)</note>
	</country>
	<country>
		<a2code>BQ</a2code>
		<name>Bonaire, Sint Eustatius and Saba</name>
		<since>2010</since>
		<note>Consists of three Caribbean "Saba (the BES Islands) Previous ISO country name: Bonaire, Saint Eustatius and Saba BQ previously represented British Antarctic Territory</note>
	</country>
	<country>
		<a2code>BR</a2code>
		<name>Brazil</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BS</a2code>
		<name>Bahamas</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BT</a2code>
		<name>Bhutan</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BV</a2code>
		<name>Bouvet Island</name>
		<since>1974</since>
		<note>Belongs to Norway</note>
	</country>
	<country>
		<a2code>BW</a2code>
		<name>Botswana</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>BY</a2code>
		<name>Belarus</name>
		<since>1974</since>
		<note>Code taken from previous ISO country name: BYAA) Code assigned as the country was already a UN member since 1945[16]</note>
	</country>
	<country>
		<a2code>BZ</a2code>
		<name>Belize</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CA</a2code>
		<name>Canada</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CC</a2code>
		<name>Cocos (Keeling) Islands</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CD</a2code>
		<name>Congo, the Democratic Republic of the</name>
		<since>1997</since>
		<note>Name changed from Zaire (ZR)</note>
	</country>
	<country>
		<a2code>CF</a2code>
		<name>Central African Republic</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CG</a2code>
		<name>Congo</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CH</a2code>
		<name>Switzerland</name>
		<since>1974</since>
		<note>Code taken from name in Confoederatio Helvetica</note>
	</country>
	<country>
		<a2code>CI</a2code>
		<name>Côte d'Ivoire</name>
		<since>1974</since>
		<note>ISO country name follows UN designation (common name: Ivory Coast)</note>
	</country>
	<country>
		<a2code>CK</a2code>
		<name>Cook Islands</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CL</a2code>
		<name>Chile</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CM</a2code>
		<name>Cameroon</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CN</a2code>
		<name>China</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CO</a2code>
		<name>Colombia</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CR</a2code>
		<name>Costa Rica</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CU</a2code>
		<name>Cuba</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CV</a2code>
		<name>Cabo Verde</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CW</a2code>
		<name>Curaçao</name>
		<since>2010</since>
		<note />
	</country>
	<country>
		<a2code>CX</a2code>
		<name>Christmas Island</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CY</a2code>
		<name>Cyprus</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>CZ</a2code>
		<name>Czechia</name>
		<since>1993</since>
		<note>Previous ISO country name: Czech Republic</note>
	</country>
	<country>
		<a2code>DE</a2code>
		<name>Germany</name>
		<since>1974</since>
		<note>Code taken from name in Deutschland Code used for West Germany before 1990 (previous ISO country name: Germany, Federal Republic of)</note>
	</country>
	<country>
		<a2code>DJ</a2code>
		<name>Djibouti</name>
		<since>1977</since>
		<note>Name changed from French Afar and Issas (AI)</note>
	</country>
	<country>
		<a2code>DK</a2code>
		<name>Denmark</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>DM</a2code>
		<name>Dominica</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>DO</a2code>
		<name>Dominican Republic</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>DZ</a2code>
		<name>Algeria</name>
		<since>1974</since>
		<note>Code taken from name in Dzayer</note>
	</country>
	<country>
		<a2code>EC</a2code>
		<name>Ecuador</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>EE</a2code>
		<name>Estonia</name>
		<since>1992</since>
		<note>Code taken from name in Eesti</note>
	</country>
	<country>
		<a2code>EG</a2code>
		<name>Egypt</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>EH</a2code>
		<name>Western Sahara</name>
		<since>1974</since>
		<note>Previous ISO country name: Sahara español)</note>
	</country>
	<country>
		<a2code>ER</a2code>
		<name>Eritrea</name>
		<since>1993</since>
		<note />
	</country>
	<country>
		<a2code>ES</a2code>
		<name>Spain</name>
		<since>1974</since>
		<note>Code taken from name in España</note>
	</country>
	<country>
		<a2code>ET</a2code>
		<name>Ethiopia</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>FI</a2code>
		<name>Finland</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>FJ</a2code>
		<name>Fiji</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>FK</a2code>
		<name>Falkland Islands (Malvinas)</name>
		<since>1974</since>
		<note>ISO country name follows UN designation due to the [17]</note>
	</country>
	<country>
		<a2code>FM</a2code>
		<name>Micronesia, Federated States of</name>
		<since>1986</since>
		<note>Previous ISO country name: Micronesia</note>
	</country>
	<country>
		<a2code>FO</a2code>
		<name>Faroe Islands</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>FR</a2code>
		<name>France</name>
		<since>1974</since>
		<note>Includes Clipperton Island</note>
	</country>
	<country>
		<a2code>GA</a2code>
		<name>Gabon</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>GB</a2code>
		<name>United Kingdom of Great Britain and Northern Ireland</name>
		<since>1974</since>
		<note>Code taken from [18] exceptionally reserved)</note>
	</country>
	<country>
		<a2code>GD</a2code>
		<name>Grenada</name>
		<since>1974</since>
		<note />
	</country>
	<country>
		<a2code>GE</a2code>
		<name>Georgia</name>
		<since>1992</since>
		<note>GE previously represented Gilbert and Ellice Islands</note>
